name: Lint Markdown Documentation
on:
  push:
    paths: ["**/*.md"]
  pull_request:
    paths: ["**/*.md"]
jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Lint markdown files
        uses: DavidAnson/markdownlint-cli2-action@v24
        with:
          globs: "**/*.md"